### ISSUE TITLE
After the straight rail is exported, it is found that the note box is not exported, and the position where the note box should be placed is the type of block used to lay the circuit

### ISSUE THREAD

**Issue by Logic922** [OpenNBS/OpenNoteBlockStudio#435] opened 2024-02-06 15:23 UTC
After the straight rail is exported, it is found that the note box is not exported, and the position where the note box should be placed is the type of block used to lay the circuit
![Uploading 2024-02-06_23.27.26.png…]()
![Uploading 2024-02-06_23.27.26.png…]()

**Comment by chenxi050402** [comment] 2024-02-06 18:45
Duplicate of #417

**Comment by Logic922** [comment] 2024-02-07 05:46
> 的副本 #417

但这似乎并未解决，我是用的是最新版

**Comment by Logic922** [comment] 2024-02-07 05:49
So, you didn’t solve this problem?
I am using the newest one : )



logic


------------------ Original ------------------
From: chenxi050402 ***@***.***&gt;
Date: Wed,Feb 7,2024 2:45 AM
To: OpenNBS/OpenNoteBlockStudio ***@***.***&gt;
Cc: Logic922 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [OpenNBS/OpenNoteBlockStudio] After the straight rail isexported, it is found that the note box is not exported, and the positionwhere the note box should be placed is the type of block used to lay thecircuit (Issue #435)





 
Duplicate of #417

**Comment by chenxi050402** [comment] 2024-02-07 05:51
next release means it's fixed in repo but not released yet

**Comment by Logic922** [comment] 2024-02-07 05:54
Oh
I know now
Thank you&nbsp;



logic


------------------ Original ------------------
From: chenxi050402 ***@***.***&gt;
Date: Wed,Feb 7,2024 1:51 PM
To: OpenNBS/OpenNoteBlockStudio ***@***.***&gt;
Cc: Logic922 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [OpenNBS/OpenNoteBlockStudio] After the straight rail isexported, it is found that the note box is not exported, and the positionwhere the note box should be placed is the type of block used to lay thecircuit (Issue #435)





 
next release means it's fixed in repo but not released yet

**Comment by chenxi050402** [comment] 2024-02-07 05:55
if you tick the command block option that'll work

**Closed** 2024-03-31 22:28 UTC
Labels: S: Duplicate
