### ISSUE TITLE
Is it possible to support Mac os or other systems in the future?

### ISSUE THREAD

**Issue by shenyx110** [OpenNBS/OpenNoteBlockStudio#397] opened 2023-05-19 12:09 UTC
Is it possible to support Mac os or other systems in the future?

**Comment by chenxi050402** [comment] 2023-05-19 12:11
Duplicate of #4

**Comment by Bentroen** [comment] 2023-05-19 12:12
Support for Mac is being worked on, but so far there's not an ETA for this as it involves a lot of work. See #4 to track the progress on this!

**Closed** 2023-05-19 12:11 UTC
