### ISSUE TITLE
Can it be compatible with more versions and play any music with one machine?

### ISSUE THREAD

**Issue by liuxing947** [OpenNBS/OpenNoteBlockStudio#420] opened 2023-09-10 07:32 UTC
Hello, the function of this tool is too old. A 5-minute music needs 200 blocks in length. I have seen many redstone music machines that can load any music in a 3*3 area, so can you change the playback mechanism and encode the notes to be played into items and pack them into shulker boxes? You only need one machine to play any music. I prefer to hear redstone music in the lobby instead of moving on the track.

**Comment by chenxi050402** [comment] 2023-09-10 15:21
Exit this repository, walk 200m, turn left, and you'll find this https://github.com/jazziiRed/nbs-converter

**Comment by Bentroen** [comment] 2023-11-28 03:36
We're tracking newer schematic export formats/layouts in #29.

Duplicate of #29

**Closed by Bentroen** 2023-11-28 03:36 UTC
