### ISSUE TITLE
Can't open/create project

### ISSUE THREAD

**Issue by ferdmusic** [OpenNBS/OpenNoteBlockStudio#436] opened 2024-02-09 12:22 UTC
**Describe the bug**
Whenever I open or create a new project I get this error:

___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_controller:

index out of bounds request 11 maximum size is 11############################################################################################
gml_Script_midi_input_set_key (line 8)
gml_Script_draw_piano (line 155)
gml_Script_control_draw (line 2274)
gml_Object_obj_controller_Draw_0 (line 0)

**To Reproduce**
1. Open up Noteblock Studio
2. Click on "Create a new song"
3. See error

**Expected behavior**
I expected a fresh project to open up

**Screenshots**

**Additional context**
I added a midi file with a lot of midi channels first. I don't know if this is the cause, it is my first time using the program. The error still appears after. Also I have a lot of midi devices connected to my computer. The error appears every time I try to do anything in the welcome screen

![grafik](https://github.com/OpenNBS/OpenNoteBlockStudio/assets/80982592/bc380123-f44e-486c-a082-b8ce5392bef8)

**Comment by ferdmusic** [comment] 2024-02-09 12:30
Edit: It appears as if the program is working on my friends computer. Also importing the midi-file works fine!

**Comment by Bentroen** [comment] 2024-03-31 22:11
Duplicate of https://github.com/OpenNBS/OpenNoteBlockStudio/issues/348: some virtual MIDI devices don't interact well with NBS and cause a crash on startup. Please check if this is the case!

**Closed by Bentroen** 2024-03-31 22:11 UTC
