### ISSUE TITLE
Export AS Midi

### ISSUE THREAD

**Issue by AvansivaYT** [OpenNBS/OpenNoteBlockStudio#431] opened 2023-11-24 16:57 UTC
I was trying to make a song using nbs when i tried to export it as midi. no option and i spent over 3 hours on it, and audio to midi tools suck. Can you add exporting as midi a thing?

**Comment by encode42** [comment] 2023-11-24 20:51
Duplicate of #13

**Closed** 2023-11-28 03:30 UTC
