### ISSUE TITLE
Can you make it for mac?

### ISSUE THREAD

**Issue by LilIndigo1** [OpenNBS/OpenNoteBlockStudio#395] opened 2023-05-16 06:04 UTC
I'm on mac and it won't allow me to open the .exe file

**Comment by chenxi050402** [comment] 2023-05-16 06:07
Duplicate of #4 and there is a test build at https://github.com/time-killer-games/OpenNoteBlockStudio/releases/tag/v0.0.0.0

**Comment by chenxi050402** [comment] 2023-05-16 06:09
or you can use a virtual machine like virtual box

**Closed** 2023-05-16 06:08 UTC
