### ISSUE TITLE
Having trouble playin!

### ISSUE THREAD

**Issue by Yexiaowei11** [OpenNBS/OpenNoteBlockStudio#341] opened 2022-07-14 06:40 UTC
Having trouble playin!
[捕获](https://user-images.githubusercontent.com/102587532/178917623-629b1666-c961-4979-8e40-13ae4ff8749e.PNG)
file with problems：
[oh Suzanna.zip](https://github.com/OpenNBS/OpenNoteBlockStudio/files/9109196/oh.Suzanna.zip)
g

**Comment by Yexiaowei11** [comment] 2022-07-14 06:41
Both the new version and the beta version have errors

**Comment by chenxi050402** [comment] 2022-07-14 06:46
duplicate of #178

**Closed by chenxi050402** 2022-07-14 06:46 UTC
