### ISSUE TITLE
command blocks AND OTHER also a option

### ISSUE THREAD

**Issue by hackerplayz124** [OpenNBS/OpenNoteBlockStudio#296] opened 2021-12-14 16:54 UTC
to make the song more accurate using diffrent types redstone  that does differnet activation and differnet  tics and command blocks

**Comment by Bentroen** [comment] 2021-12-14 20:54
Duplicate of #29

**Closed by Bentroen** 2021-12-14 20:54 UTC
Labels: Type: Enhancement

**Comment by hackerplayz124** [comment] 2021-12-15 02:08
this is not a duplicate

**Comment by Bentroen** [comment] 2021-12-15 17:19
What you described seems to be using other kinds of redstone contraptions to make playback more accurate, as well as using command blocks to be able to play custom sounds and out-of-range notes.

Although these are not mentioned in the issue above, both of those features are planned for the upcoming schematic rewrite.

If I misunderstood your request, feel free to clarify it!

**Comment by Bentroen** [comment] 2021-12-15 17:21
I'm sorry, this would've been better flagged as a duplicate of #53!
