### ISSUE TITLE
"Get extra notes pack" option when exporting datapack not working

### ISSUE THREAD

**Issue by Johnny9926** [OpenNBS/OpenNoteBlockStudio#316] opened 2022-03-21 04:06 UTC
When I pressed "Get extra notes pack", it asked me where to save it, and when I pressed save, it said "Resource pack saved successfully", but there was no resource pack in the folder

**Comment by chenxi050402** [comment] 2022-03-21 04:08
Duplicate of #299

**Closed by chenxi050402** 2022-03-21 04:08 UTC

**Comment by chenxi050402** [comment] 2022-03-21 04:10
You can get the pack [here](https://github.com/HielkeMinecraft/OpenNoteBlockStudio/blob/HEAD/datafiles/Data/extranotes.zip?raw=true)
