### ISSUE TITLE
ADD SUPPORT FOR MAC >>>:((((

### ISSUE THREAD

**Issue by DownloadGreenSoftware** [OpenNBS/OpenNoteBlockStudio#352] opened 2022-08-25 16:09 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the enhancement you'd like**

**Additional context**

**Comment by chenxi050402** [comment] 2022-08-25 16:12
Duplicate of #4

**Closed by chenxi050402** 2022-08-25 16:12 UTC
