### ISSUE TITLE
Sound Error

### ISSUE THREAD

**Issue by prakeshkumar15633** [OpenNBS/OpenNoteBlockStudio#480] opened 2024-10-06 06:23 UTC
Issue with bluetooth. When connected with bluetooth after opening the app music playing in laptop speaker but not bluetooth. When disconnected bluetooth after opening app, music not playing in laptop speaker.

1. Connect Bluetooth
2. Open App
3. Disconnect Bluetooth
4. Play music
5. Music not audible
or
1. Disconnect Bluetooth
2. Open app
3. Connect Bluetooth
4. Play music
5. Music playing in laptop speaker but not in bluetooth

**Expected behavior**
Music playing from laptop speaker or Music playing in bluetooth

**Comment by Bentroen** [comment] 2024-10-06 06:54
Duplicate of #244. Sorry, NBS can't detect when you change your audio output device at the moment, so you have to restart the app if you switch your default audio device!

**Closed by Bentroen** 2024-10-06 06:54 UTC
