### ISSUE TITLE
I want use

### ISSUE THREAD

**Issue by say-annyeong** [OpenNBS/OpenNoteBlockStudio#425] opened 2023-09-30 22:47 UTC
**Describe the bug**
action number 1

**To Reproduce**
1. click to create a new song

**Expected behavior**
load a song, generate song out of MIDI file

**Screenshots**
![이미지_2023-10-01_074257155](https://github.com/OpenNBS/OpenNoteBlockStudio/assets/86085202/513cd65b-5f5d-4940-aa0d-cb1ef8118033)

**Additional context**
uh...

**Comment by Bentroen** [comment] 2023-11-28 03:57
Hi! Thanks for reporting the issue; sorry for the inconvenience.
I happened to notice a lot of "Internal MIDI" devices in your screenshot. I believe they could be interfering in the startup since NBS may not know how to handle them. Could you try disabling the thing it's coming from? (I'd be interested in knowing what is it so I can try to replicate the issue).

**Comment by Bentroen** [comment] 2023-11-28 04:00
Duplicate of #348

**Closed** 2023-11-28 04:00 UTC
Labels: S: Duplicate
