### ISSUE TITLE
Feature Request: Comments

### ISSUE THREAD

**Issue by TrapinchO** [OpenNBS/OpenNoteBlockStudio#175] opened 2020-07-26 19:40 UTC
**Is your feature request related to a problem? Please describe.**
There is a problem (especially with longer songs) when you lose track of where you are and need to find it from the beggining.

**Describe the enhancement you'd like**
Add little marker (like new "instrument") that would display text when hovered over with mouse. It would be completely skipped when exporting (like comments in program's code).

**Additional context**
none

**Comment by Bentroen** [comment] 2020-07-29 02:03
Related to #122 (may be implemented similarly)

**Comment by Bentroen** [comment] 2023-06-02 13:53
Duplicate of #122

**Closed by Bentroen** 2023-06-02 13:53 UTC
Labels: C: Enhancement
