### ISSUE TITLE
Solo layers in drop mode

### ISSUE THREAD

**Issue by BedrRedstone** [OpenNBS/OpenNoteBlockStudio#472] opened 2024-08-30 22:35 UTC
So, what I think would be cool, would be if you could solo layers or solo groups of layers with the same name in the drop mode Ex: solo "bass" to solo like 20 layers named "bass". it could give some more functionality to the layer names

**Comment by Bentroen** [comment] 2024-08-31 00:15
This is planned in a future redesign of layers. However, we can't just 'arbitrarily' add features that target layers with the same name, without adding a feature to group layers in a more prominent way. Otherwise we'd end up with lots of unofficial 'quirks' about how certain features of the program works, in ways that are less than ideal (just like what happened with tempo changers).

I'm going to close this issue as a duplicate of #464 (also by you) just so we can track its progress there :)

**Closed by Bentroen** 2024-08-31 00:15 UTC
