### ISSUE TITLE
Feature Request: Export as OGG

### ISSUE THREAD

**Issue by octahedron80** [OpenNBS/OpenNoteBlockStudio#82] opened 2019-08-27 14:26 UTC
Since we have .ogg as instruments, why we do not have a simple export option for .ogg as result? 😉

PS. Please do not ask me to convert it myself, since the conversion always loses audio quality.

**Comment by Bentroen** [comment] 2023-06-02 13:35
The new audio export in 3.10.0 adds support for multiple formats, but .ogg was left out due to the Vorbis codec support. Closing as a duplicate of #344 which is more up-to-date.

**Comment by Bentroen** [comment] 2023-06-02 13:35
Duplicate of #344

**Closed by Bentroen** 2023-06-02 13:35 UTC
Labels: C: Enhancement
