### ISSUE TITLE
Supports Redstone Repeater as the unit of spacing between note blocks

### ISSUE THREAD

**Issue by x-yingcan-x** [OpenNBS/OpenNoteBlockStudio#325] opened 2022-04-16 15:33 UTC
I know it's difficult and it's a milestone feature, but I still hope you can make it soon.
You need to use Redstone repeaters as units when doing Redstone music, but NBS simply makes the TPS limited to 2.5t/s, 5t/s, 10t/s, and while that works, it's not concise and it's a pain to adjust.
I would even like to be able to import pentameters if possible
(I apologise for the mechanical translation)

**Comment by chenxi050402** [comment] 2022-04-16 15:59
Thanks for reporting the issue!
While it's easier to make the music in-game by using units in repeaters, NBS also supports tempo incompatible in Minecraft that cannot be represented with repeater counts. Maybe you can just count the spaces between notes and place the blocks accordingly (1 one-tick repeater/space for 10t/s, 1 two-tick repeater/space for 5t/s, and 1 four-tick space for 2.5t/s).

还有，是国人的话可以直接用中文的 (Ignore if you don't understand)

**Comment by x-yingcan-x** [comment] 2022-04-16 17:12
> Thanks for reporting the issue! While it's easier to make the music in-game by using units in repeaters, NBS also supports tempo incompatible in Minecraft that cannot be represented with repeater counts. Maybe you can just count the spaces between notes and place the blocks accordingly (1 one-tick repeater/space for 10t/s, 1 two-tick repeater/space for 5t/s, and 1 four-tick space for 2.5t/s).
> 
> 还有，是国人的话可以直接用中文的 (Ignore if you don't understand)

换算间隔简单，但调间隔麻烦。想的是多一个中继器的格子，滚轮调档位，不使用固定的TPS/BPM，所以说我觉得很难。
（而且我万万没想到作者是国人，回复还这么快）

**Comment by chenxi050402** [comment] 2022-04-16 17:16
用调中继器这种方式还是直接在游戏里做好吧，再用个音符盒显示的材质包和blocktuner很方便
这种方式目前在nbs里很难实现（因为nbs是用tick数计算时间的并且要改的话基本得重写，4.0会用python重写，也许可以考虑一下）

**Comment by Bentroen** [comment] 2022-06-09 00:29
Duplicate of #29

**Closed by Bentroen** 2022-06-09 00:29 UTC
