### ISSUE TITLE
Code error when importing a new midi file into nbs

### ISSUE THREAD

**Issue by Obsidoogithub** [OpenNBS/OpenNoteBlockStudio#321] opened 2022-04-03 05:44 UTC
**Describe the bug**

**To Reproduce**
1. Import any custom .mid file
2. play
3. See error

**Expected behavior**
Playing the song like normal

**Screenshots**

**Additional context**

**Comment by Bentroen** [comment] 2022-04-05 00:30
Hi, and thanks for reporting the issue!

Could you please attach the affected MIDI file here? We need to inspect it in order to determine what's causing the problem. :)

**Comment by DiaxManPl** [comment] 2022-07-05 18:18
I have the same issue, @Bentroen here is my midi file: https://onlinesequencer.net/app/midi.php?id=2660660

**Comment by chenxi050402** [comment] 2022-07-06 06:57
> Error:
> 
> ```
> 
> ___________________________________________
> ############################################################################################
> ERROR in
> action number 1
> of Draw Event
> for object obj_controller:
> 
> Push :: Execution Error - Variable Index [255] out of range [128] - -1.midi_ins(100607,255)
> at gml_Script_open_midi
> ############################################################################################
> gml_Script_open_midi (line -1)
> gml_Script_draw_window_greeting
> gml_Script_draw_windows
> gml_Script_control_draw
> gml_Object_obj_controller_Draw_0 (line -1)
> ```

The Loose Hi-Hat of the instrument 2013 Drum kit in onlinesequenser when imported to midi has a instrument id of 255, which is illegal according to the midi specification. Try using another instrument when exporting.

**Comment by chenxi050402** [comment] 2022-07-07 05:17
Also duplicate of #285

**Closed** 2022-07-07 06:00 UTC
Labels: C: Bug
