### ISSUE TITLE
When attempting to close Note Block Studio via the windows taskbar, It freezes

### ISSUE THREAD

**Issue by BeastyBoss-303** [OpenNBS/OpenNoteBlockStudio#364] opened 2022-11-05 07:34 UTC
**Describe the bug**
When attempting to close Note Block Studio via the windows taskbar, It freezes, the window goes black and is then unable to be closed without Task Manager.

**To Reproduce**
1. Open Note Block Studio
2. Try to close it via the windows taskbar (**by right clicking and pressing close window**)

**Expected behavior**
The window should close like normal

**Screenshots**
No screenshots needed

**Additional context**
when closing via hovering over the application on the taskbar and pressing the "X" it works as intended, though not when right clicking and selecting close window.

**Comment by Bentroen** [comment] 2022-11-22 04:52
Thank you for your detailed report!
I can't reproduce this bug -- have you noticed if it happens when you're doing something specific, like in the middle of a long operation? Also, what's the Windows version you're running?

**Comment by BeastyBoss-303** [comment] 2022-11-27 05:06
try to close it this way during a song playing, also windows 10

**Comment by Bentroen** [comment] 2022-11-28 22:25
Note Block Studio emits a popup asking if you want to save the song, but sometimes (especially if you have multiple monitors) it appears minimized, hidden under the main window, or in a different screen. While the popup is open, the window stops drawing itself, freezes and _may_ become black if you resize it. Are you sure it's not this popup preventing NBS from closing?

![image](https://user-images.githubusercontent.com/29354120/204393839-c75c7103-641e-454f-8796-08941f54bb51.png)

**Closed** 2023-06-02 13:14 UTC
Labels: C: Bug, S: Needs further investigation
