### ISSUE TITLE
The extra notes and not block textures download doesn't work

### ISSUE THREAD

**Issue by superJK921** [OpenNBS/OpenNoteBlockStudio#300] opened 2021-12-23 17:32 UTC
**Describe the bug**
The extra notes and not block textures download doesn't work

**To Reproduce**
1. Go to 'File'
2. Click on 'Export as Data Pack'
3. Scroll down to 'Get Extra Notes Pack' and then go to 'Visualizer' the click 'Get Noteblock Textures' 

**Expected behavior**
The 'Extra Notes' and 'note block textures' pack doesn't download

**Comment by chenxi050402** [comment] 2021-12-24 10:39
Duplicate of #299

**Closed by chenxi050402** 2021-12-24 10:39 UTC
Labels: Type: Bug
