### ISSUE TITLE
MacOS Addition

### ISSUE THREAD

**Issue by IDrewEvenly** [OpenNBS/OpenNoteBlockStudio#458] opened 2024-07-06 20:19 UTC
Ive been looking for a note block editior for a long time, and then I went onto Hypixel Fourms and saw someone suggest this, I was happy until I downloaded it and my computer said it was for Windows only. Like come on, is MacOS like not that common for computers or something??

Please make this MacOS Available. I dont know that much about coding, little to none actually. But if this is made in Gamemaker, you should be able to make this MacOS Available.

![Screen Shot 2024-07-06 at 4 17 05 PM](https://github.com/OpenNBS/OpenNoteBlockStudio/assets/174634953/4acd9a25-75a9-42ba-85d4-1fb76afd2455)

**Comment by encode42** [comment] 2024-07-07 20:40
Duplicate of https://github.com/OpenNBS/OpenNoteBlockStudio/issues/4, various cross-platform versions are in-development

**Comment by ChicknTurtle** [comment] 2024-07-20 18:39
I use Whisky to run on mac (a bit janky but it works)

**Comment by HeChuan404** [comment] 2024-07-21 19:00
no comment

**Closed** 2024-07-31 03:26 UTC
