### ISSUE TITLE
Extra Note Block Resource Pack not downloading

### ISSUE THREAD

**Issue by ItsTyphoonnn** [OpenNBS/OpenNoteBlockStudio#331] opened 2022-05-19 14:34 UTC
Whenever I download the extra note block resource pack it says its downloaded but when i go to my downloads folder it isnt there and i can't find it anywhere no matter what i do. but for some reason on the quick search area it shows it but when i drag it to my desktop it shows this: 
![Screenshot (38)](https://user-images.githubusercontent.com/104877824/169321846-a82e8cae-1437-468a-a514-c1d48af53a1e.png)
)

**Comment by chenxi050402** [comment] 2022-05-19 14:39
It's an issue with the current stable version, you can try downloading the development version and try again or download the resourcepack [here](https://github.com/HielkeMinecraft/OpenNoteBlockStudio/blob/HEAD/datafiles/Data/extranotes.zip?raw=true)

**Comment by Bentroen** [comment] 2022-07-08 10:10
Duplicate of #299

**Closed by Bentroen** 2022-07-08 10:10 UTC
