### ISSUE TITLE
Issue trying to export

### ISSUE THREAD

**Issue by PkSt4rstorm** [OpenNBS/OpenNoteBlockStudio#405] opened 2023-06-08 22:43 UTC
![image](https://github.com/OpenNBS/OpenNoteBlockStudio/assets/136029953/51fc7a25-60ed-40fb-b5c3-ef3f7ee90cb5)

I've tried reinstalling just about 14 times now, this has been an issue for months. I've searched high and low for something to fix it, but I just can't find anything. It was working fine before I moved everything to dropbox. I tried moving everything back, and that didn't fix it. It's just broke now, and I don't know what else to do.

**Comment by Bentroen** [comment] 2023-06-09 04:57
Thank you for reporting the issue, and sorry for the inconvenience! We're already tracking this issue somewhere else, so I'll be closing it as a duplicate.

Duplicate of #367

**Closed by Bentroen** 2023-06-09 04:57 UTC

**Comment by Bentroen** [comment] 2023-06-09 04:58
Duplicate of #367
