### ISSUE TITLE
Audio always played by computer speakers when headphones are connected

### ISSUE THREAD

**Issue by Floog98** [OpenNBS/OpenNoteBlockStudio#450] opened 2024-05-05 23:01 UTC
**Describe the bug**

**To Reproduce**
1. Connect your headphones
2. Start playing a song
3. Then realize it's playing in the speakers of the computer and not the headphones

**Expected behavior**
I thought it would play in headphones.

**Screenshots**
Sorry i can't import screenshots because that won't show the problem

**Comment by Bentroen** [comment] 2024-07-31 03:29
Duplicate of #244

**Closed by Bentroen** 2024-07-31 03:29 UTC
