### ISSUE TITLE
Cant change sound device per application in windows settings

### ISSUE THREAD

**Issue by nanaroru** [OpenNBS/OpenNoteBlockStudio#432] opened 2023-11-28 02:49 UTC
**Describe the bug**
Changed the sound device in Windows settings but it's still hear from the default device.

**To Reproduce**
Change your Windows settings

**Expected behavior**
When changing the sound device in Windows settings, it must be heard from the changed device.

**Screenshots**
![スクリーンショット 2023-11-28 114512](https://github.com/OpenNBS/OpenNoteBlockStudio/assets/146121689/baa2998f-285e-49e6-b47d-17f19bace03d)
Sorry, my language is Japanese.
This page is "Windows Settings > System > Sound > App volume and device preferences

**Additional context**
None

**Comment by nanaroru** [comment] 2023-11-28 02:53
Would it be better to make a page about "Add Switch Sound Device" to Feature suggestion?

**Comment by Bentroen** [comment] 2023-11-28 03:30
Thanks for reporting the issue! We're already tracking this problem in another issue, so I'll be closing this one.

Duplicate of #243

**Closed by Bentroen** 2023-11-28 03:30 UTC
