### ISSUE TITLE
a bug when compressing selection,i only can abort my song.....

### ISSUE THREAD

**Issue by username-su** [OpenNBS/OpenNoteBlockStudio#465] opened 2024-08-09 07:32 UTC
___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_menu:

index out of bounds request 8 maximum size is 8############################################################################################
gml_Script_selection_code_update (line 13)
gml_Script_selection_compress (line 89)
gml_Script_menu_click (line 145)
gml_Script_menu_draw (line 188)
gml_Object_obj_menu_Draw_0 (line 0)
![image](https://github.com/user-attachments/assets/6cf16388-9150-4a36-b8e2-3f6cc1d77799)

**Comment by Bentroen** [comment] 2024-08-09 17:09
Thanks for reporting the issue, and sorry for the inconvenience

Duplicate of #44

**Closed** 2024-08-09 17:09 UTC
