### ISSUE TITLE
[Bug] Sometimes the compress section feature doesn't work (pre-release)

### ISSUE THREAD

**Issue by I21b** [OpenNBS/OpenNoteBlockStudio#468] opened 2024-08-19 23:37 UTC
**Describe the bug**

If the section contains some notes in `special placements`, `compressing` it will `crash the program` or `results in fewer notes`.
Most of the time, it results in fewer notes, in some special placements, the program will crash.

**To Reproduce**

1. Place some notes (3 or more)
2. Select these notes and compress it in the right-click menu
3. Repeat step 2
4. If nothing happened, try another placement

**Expected behavior**

Compress it until the notes become a vertical line

**Screenshots**

Crash
![Crash](https://github.com/user-attachments/assets/5e3c505d-e1ac-4679-947a-6ea34ae92712)
(0:19)

Fewer
![Fewer](https://github.com/user-attachments/assets/fe10ae0a-1eee-432e-91f3-046787a349e6)
(0:12)

**Additional context**

Window 11 23H2 (64 x64)
**3.11.0 Beta 2**

<details>
<summary>Logs</summary>

```

___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_menu:

index out of bounds request 4 maximum size is 4############################################################################################
gml_Script_selection_code_update (line 27)
gml_Script_selection_compress (line 89)
gml_Script_menu_click (line 146)
gml_Script_menu_draw (line 188)
gml_Object_obj_menu_Draw_0 (line 0)

```

</details>

Does nbs has auto save? 😭

**Comment by Bentroen** [comment] 2024-08-31 00:24
Related to #44

**Comment by Bentroen** [comment] 2024-08-31 00:25
Duplicate of #44

**Closed by Bentroen** 2024-08-31 00:25 UTC
Labels: C: Bug
